# Stub for volume_profile indicator
from typing import Any, Optional

class VolumeProfileCalculator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def calculate(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def get_trading_signals(self, *args: Any, **kwargs: Any) -> Any: ...

class VolumeProfileIndicator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def calculate(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
