# Stub file for mypy - fair_value_gaps has type issues
from typing import Any, Optional

class FairValueGapsCalculator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def calculate(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
