# Stub file for mypy - factory has type issues
from typing import Any, Optional

def create_indicator(*args: Any, **kwargs: Any) -> Optional[Any]: ...
def calculate_sma(*args: Any, **kwargs: Any) -> Optional[Any]: ...
def calculate_ema(*args: Any, **kwargs: Any) -> Optional[Any]: ...
def calculate_rsi(*args: Any, **kwargs: Any) -> Optional[Any]: ...
