# Stub file for mypy - cache has type issues
from typing import Any, Optional, Dict

class IntelligentCache:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def set(self, *args: Any, **kwargs: Any) -> None: ...
