# Stub file for mypy - economic.py has legacy code patterns
# TODO: Refactor economic.py for complete type safety

from typing import Any, Optional, List

class AsyncEconomicCalendarRSSParser:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def parse_rss_feeds(self) -> List[dict[str, Any]]: ...
    async def get_economic_events(self) -> Optional[List[dict[str, Any]]]: ...

class EconomicEventsProvider:
    def __init__(self) -> None: ...
    async def get_events(self) -> Optional[List[dict[str, Any]]]: ...
