# Stub file for mypy - OBV indicator has type issues
# TODO: Refactor OBV for complete type safety

from typing import Any, Optional

class OBVCalculator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_data_point(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def get_current_value(self) -> Any: ...

class OBVIndicator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def calculate(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def generate_signal(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
