# Stub file for mypy - SuperTrend indicator has complex type issues
# TODO: Refactor SuperTrend for complete type safety

from typing import Any, Optional

class SuperTrendCalculator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_data_point(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def get_current_value(self) -> Any: ...

class SuperTrendIndicator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def calculate(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def generate_signal(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...

class SuperTrendPlotter:
    @staticmethod
    def plot(*args: Any, **kwargs: Any) -> Any: ...
