# Stub file for mypy - RSI indicator has type issues
# TODO: Refactor RSI for complete type safety

from typing import Any, Optional

class RSICalculator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_data_point(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def get_current_value(self) -> Any: ...

class RSIIndicator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def calculate(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def generate_signal(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
