# Stub file for mypy - rate_limiter has type issues
from typing import Any, Optional, Dict

class RateLimiter:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def is_rate_limited(self, *args: Any, **kwargs: Any) -> bool: ...
    def get_stats(self) -> Dict[str, Any]: ...
