# Stub for squeeze indicator
from typing import Any, Optional

class SqueezeConfig:
    pass

class SqueezeCalculator:
    def __init__(self, config: SqueezeConfig) -> None: ...
    def add_data_point(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def calculate_from_data(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...

class SqueezeIndicator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def calculate(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
