# Stub file for mypy - squeeze calculator has type issues
from typing import Any, Optional

class SqueezeCalculator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_data_point(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def calculate(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
